### PR TITLE
readme update to reflect nixpkgs packaging

### PR DESCRIPTION
**Pull request by helium18**
**What**: Packaged `gh-eco` for Nixpkgs :)

**Why**: Installing extensions from `gh` doesn't work on NixOS (Read only file system). Therefore I decided to package it.

**How**: updated the README (actual PR: https://github.com/NixOS/nixpkgs/pull/175699/files)

**Checklist**:

- [x] `Allow edits from maintainers` option checked 
- [x] Branch name is prefixed with `[your_username]/` (ex. `coloradocolby/featureX`)
- [ ] Documentation added N/A
- [ ] Tests added N/A
- [ ] No failing actions N/A
- [x] Merge ready

### CODE REVIEW

**Comment by jrnxf** [comment]
Hey thanks for doing this! Will this need to be updated every release?

**Comment by helium18** [comment]
yes!

**Comment by jrnxf** [comment]
@helium18 do you have any documentation on how I can do that? Given you already created it I'm not sure if that means you'd be the one to constantly update it? I don't want to have to do that to you 😅

**Comment by helium18** [comment]
here's the documentation for the go module 
https://ryantm.github.io/nixpkgs/languages-frameworks/go/

the `default.nix` file is located in `pkgs/tools/misc/gh-eco`
You just need to update the `version` field and empty the `sha256` and `vendorSha256` fields 

Then go to the repo root and run `nix build -A gh-eco`. This should fail with an error on the lines of `specified Sha=<some_random_sha>` `got <some_sha>`. So now you can fill the missing fields (which are `sha256` and `vendorSha256`) in `default.nix` and finally run `nix build -A gh-eco` again and it should work now

Test the package by running `./result/bin/gh-eco` in the repo root. If everything runs fine, you can now submit a PR

https://nixos.wiki/wiki/Nixpkgs/Create_and_debug_packages

I'll update the package since its a simple go module, so you don't need to worry :+1:

**Comment by jrnxf** [comment]
Picked this back up today to fix a few bugs, and I'm not sure I love the dependency on you here (nothing against you _at all_) If I push a fix up and the nix package never gets updated, that wouldn't be great imo. Would rather maintain one myself, but also don't know how much a need there is for it to be a nixpkgs. If the ask comes up again I'll reconsider!

**Pull request closed without merging**
